### ISSUE TITLE
End on 'end' vs 'finish'

### ISSUE THREAD

**Issue by coyotte508** [bendrucker/stream-to-promise#21]
I recently encountered a problem while using the library. I'm uploading a file on mongodb, using their gridfs api, detecting the end of the upload with this library and then querying the file information.

The problem is that I was too early in querying the file information on mongodb: even though I had finished transmitting the data, mongodb wasn't done processing it. 

I solved it by using the `finish` event instead of the `end` event:

```js
const bucketName = "files";

bucket = new mongo.GridFSBucket(mongoose.connection.db, {bucketName});
const upStream = bucket.openUploadStream(filename, options);
fileStream.pipe(upStream);

// await streamToPromise(upStream) <-- finishes too early!
await new Promise((resolve, reject) => {
    upStream.on("finish", () => resolve()); // `end` event would finish too early
    upStream.on("error", err => reject(err));
});

mongoose.connection.db.collection(`${bucketName}.files`).find({_id: upStream.id}).toArray((err, [info]) => {
    // info would be undefined if I has stopped waiting at the 'end' event
}
```

As said in the [doc](https://nodejs.org/api/stream.html#stream_event_finish):

> The '`finish`' event is emitted after the stream.end() method has been called, and all data has been flushed to the underlying system.

So, I don't know if it's better to switch to using `finish` to detect the end of the stream? I mean, I understand why you might want to keep using `end` as it finishes faster, but the `finish` event truly signifies the end of the processing.

**Comment by bendrucker** [comment]
Hi, if you look at the code you'll see that [end-of-stream](https://github.com/mafintosh/end-of-stream) handles the task of waiting for the stream to finish. I don't pick events and manage state. It's a lot more complicated than you've described.

Read the code there and you'll see that it properly tracks both the finish and end events depending on the type of stream.

I don't really have time to look into the particulars of mongo and in what way that stream is misbehaved. eos is massively depended on and I trust it to do the right thing here.
