### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by ryacobi** [bendrucker/stream-to-promise#30]
Hi, using stream-to-array and resolving the promise with the data from the stream means loading all of this data to memory, which can be very expensive. Sometimes I only need to know when the stream is finished, so if it was possible to resolve the promise without the data (or even only buffer length) it could be useful as well.
Wdyt? I can go ahead and add another interface for that, if you like the idea

**Comment by Marsup** [comment]
Why not use https://www.npmjs.com/package/end-of-stream-promise ?

**Comment by ryacobi** [comment]
Good point, I wasn't aware of this package
