### ISSUE TITLE
 `streamToPromise` fails when used with an object stream.

### ISSUE THREAD

**Issue by angrycat9000** [bendrucker/stream-to-promise#45]
`streamToPromise` fails when used with an object stream.    We were using `streamToPromise` to await a stream bein.

### Sample Code
```js
const streamToPromise = require("stream-to-promise");
const {Readable} = require('stream');

module.exports = { test };

async function test() {
    const stream = new Readable();
    stream.push({value:'yes'});
    await streamToPromise(stream);
}

test().catch(console.error);
```

### Error
> TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Object

**Comment by bendrucker** [comment]
If you look at the stack trace you'll see it's `stream.push` that throws, `streamToPromise` is never even called...

https://nodejs.org/api/stream.html#object-mode

> All streams created by Node.js APIs operate exclusively on strings, [Buffer](https://nodejs.org/api/buffer.html#class-buffer), [TypedArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray) and [DataView](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView) objects

> It is possible, however, for stream implementations to work with other types of JavaScript values (with the exception of null, which serves a special purpose within streams). Such streams are considered to operate in "object mode".

> Stream instances are switched into object mode using the objectMode option when the stream is created. 

And then there's the test coverage:

https://github.com/bendrucker/stream-to-promise/blob/3d305c97d9d70b8fcdc221b1a02fee0f1271c72c/test-readable.js#L64-L75
